Main: CPU.v InstructionRAM.v ControlUnit.v Reg_memory.v ALU.v  MainMemory.v InstructionFetch.v InstructionDecode.v Excution.v Memory.v WriteBack.v test_CPU.v Pipe.v HazardUnit.v wire.v
	iverilog -o Main CPU.v InstructionRAM.v  ControlUnit.v Reg_memory.v ALU.v  MainMemory.v InstructionFetch.v InstructionDecode.v Excution.v Memory.v WriteBack.v test_CPU.v Pipe.v HazardUnit.v wire.v
	vvp Main